Revert "Bump io.jenkins.plugins:custom-folder-icon from 2.10 to 2.11 in /bom-weekly (#2793)"
Test fails on Jenkins weekly and Jenkins 2.426.1 with the message:

Caused: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/configfiles/GlobalConfigFiles

This reverts commit d3dba88864c7d53ed44086e8c09e9f80603e181b.